### ISSUE TITLE
大学习绑定了微信openid

### ISSUE THREAD

**Issue by Zzzz0077** [xiaoWangSec/jx-qndxx#1]
现在大学习绑定了微信的openid，一次只能学一个人，不能像之前那样批量学习了，有啥方法可以绕过检测嘛，管理后台地址：http://106.225.141.143:8103/pub/login

**Comment by xiaoWangSec** [comment]
没办法绕过, 似乎想要成功在后台插入学习记录还需要有获取学习积分的请求, 该请求必须要用有效的openid才可以成功
目前只能收集openid后批量学习了

**Comment by Zzzz0077** [comment]
作者大大，我刚刚试了一下这个程序，后台还是没有记录到打卡数据，可能还是我哪里没弄好，方便的话加一个微信嘛，团支书真的很需要！！！有偿

**Comment by Zzzz0077** [comment]
> 没办法绕过, 似乎想要成功在后台插入学习记录还需要有获取学习积分的请求, 该请求必须要用有效的openid才可以成功 目前只能收集openid后批量学习了
