### ISSUE TITLE
好像不能补学之前的

### ISSUE THREAD

**Issue by xiaoyangsheyuan** [xiaoWangSec/jx-qndxx#11]

**Comment by Zzzz0077** [comment]
有解决办法嘛

**Comment by xiaoWangSec** [comment]
可以提供userid让我看看

**Comment by Zzzz0077** [comment]
"163AE79E49EE46D0ABC8B3A5FB5A33BD",
"oWtPk5j_BMzUcLYi8kJNuMYge1to",
"oWtPk5tuMkjNUZfB_6wsE32W8WeE",
"B14152C79D0D4475962F0B33F8439943",
"6EB7243F978D4F4A80CA9FA7729A06E1",
"7B495527BFA047E590C9AF6EE1E15AF1",
"oWtPk5q5HSWUR5jHmEuDgueKlndo",
"93F01E44DB4A47C2A971EC2F6505F5F0",
"413299766C124E38A9DBFBEC9D356642",
"C96928C670A7444CB3C54595C6281D9C",
"oWtPk5ortBdHKf2Z53YINB8GSgCo",
"E1689B4B7107472BAACF12318DF421CF",
"9F999BE6567442C1B44B9147B749AFDE",
"oWtPk5tZhBvqiCnuhp8QB9OzQR0c",
"8A42A10063A1472490F5BD7F445B7D19",
"68A8CA00765D49E497A11466F317C7FD",
"AB13CA4D9A994E81853DE83D26925953",
"0F2C63794D1C471784FC5338653D5366",
"5F2B40A7571F4CB3A7C28748BC5EA61C",
"99B85927FE3F455587DBB8EC4AA81AC3",
"oWtPk5jZKjE8d3bIGGhfxiFoIN7o",
"oWtPk5tv8zD16IYiobbRTX98z9vM",
"CA9AC3D18C634EBBA08EDEB45DDF95B0",
"oWtPk5vnUkMgpNdo2kSaH9aqWGyE",
"EDB49A74553F4ED7A4D0D7D9098D7F50",
"CA9A716BA386466BBB30C02A82629B34",
"F78263E76B99421DB75E1B7B1CB88C85",
"oWtPk5k6mSm8F3fSTNiAR_0g7dUk",
"061E949692D24A088D1B6636107B3EA6",
"oWtPk5mD1KvhWEBSUAU2GwLdmPiA",
"oWtPk5th6xlEC1CX_EpKub2D5LBM",
"DB2AD552D609488286832F51B5D371D1",
"oWtPk5jVY84W0vK5UIV0n0V9yJzc",
"88ED0FF4CCD542E2AB74C3725B86588B",
"CFD7591F271844878DFD9FFFE84A4301",
"E4841015418041409A1A91DF29E79C7F",
"oWtPk5j6xPQyOXvZvYRIZVndumEA",
"155B705392034710976C654F412B7BCF",
"oWtPk5sX01A-ilbu31ehfMoDOzHE",
"632C1FE6918749B9BD5665F4D0ECE315",
"0818BBBE31654D55957D9FBC07C5F5B9",
"8A515E83950F427B9A1C14AD34E37BC8",
"2815E8938CEF44DC873F43BD81B83505",
"EAFA43EE964443DE9C91126F99FE941C",
"oWtPk5oeR0EvhE4gLJwUUtW4rlDA",
"C75BA6D2D63D49CF8134C9E9E23CCD37",
"1315DCBC28C3434F979A7A98814D3BCC",
"oWtPk5hGbCQQP_GluQpI-1JK5hwQ",
"oWtPk5hrAMyaRgJ5_m-_qSaIwsFg",
"oWtPk5nljMxamNHV_oGXc4dHwFH4",
这是一部分的userid，作者大大能看看嘛，程序运行的时候确实是显示补学期数已完成，但是从后台数据看没任何变化，还是只能对当前期数进行学习打卡

**Comment by xiaoWangSec** [comment]
https://github.com/xiaoWangSec/jx-qndxx/blob/master/appletYouthStudy.py#L88 
应该已经可以实现补学了

**Comment by Zzzz0077** [comment]
我刚刚试了一下，后台还是没记录，但是程序是显示打卡成功
![微信截图_20240523165457](https://github.com/xiaoWangSec/jx-qndxx/assets/131767959/b2a6b46b-6712-4164-8f7e-7f6b7cc5ba9c)

**Comment by Zzzz0077** [comment]
代码确实有一点修改，方便我这边批量打卡，因为人数有点多，经常会出错中断程序，但是核心的 def learningRecords，def addOrUpdateCourse，def retakesList这些函数都没动，我刚刚也对照了你更新的代码，确实没有大的改动，因为我对Python也不太懂，只能做一些小范围的修改

**Comment by xiaoWangSec** [comment]
> https://github.com/xiaoWangSec/jx-qndxx/blob/master/appletYouthStudy.py#L88 应该已经可以实现补学了

修改部分在这里标注出来了

**Comment by Zzzz0077** [comment]
你标注的这里我是原原本本的复制粘贴过去的，程序也能正常运行，要不我把程序代码发给你看一下，看看能不能帮我找找问题，然后我刚刚在后台系统看到，这个ID的人01HNCBPM1A2ZRNWJ0M7757WTAQ，进行了补学，而且补学到了2023年的期数，但是也只有他一个人补学成功了。
我把我的代码附在下面
`
import json
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
stuInfo = []
def read_user_data(file_name):
    try:
        with open(file_name, 'r', encoding='utf-8') as reader:
            userlist = json.load(reader)
    except FileNotFoundError:
        print(f"{file_name} 文件不存在")
        userlist = {}
    except json.JSONDecodeError:
        print(f"{file_name} 文件格式不正确")
        userlist = {}

    return userlist
def sessionBuilder(openid: str):
    session = requests.session()
    session.headers = {
        "Connection": "keep-alive",
        # "Content-Length": "",
        "Authorization": openid,
        "charset": "utf-8",
        "requesttype": "",
        "openid": openid,
        "content-type": "application/json",
        "Accept-Encoding": "gzip,compress,br,deflate",
        "Referer": "https://servicewechat.com/wx88ccb2655c6720e2/51/page-frame.html",
        "User-Agent": "Mozilla/5.0 (Linux; Android 7.1.1; MI 6 Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/6.2 TBS/043807 Mobile Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN miniProgram"
    }
    session.verify = False # 如果需要开代理或者抓包请将其设置为False
    return session
def retakesList(r: requests.Session):
    try:
        url = "https://www.jxqingtuan.cn/api-client/classRecord/retakesList"
        response = r.get(url)
        response.raise_for_status()  # 将触发HTTP错误异常
        result = response.json()['data']['JxgqtClassVoList']
        lst = []  # 存放未学习期数
        for item in result:
            if item['learn'] == False:  # 还没学的
                per = {"d": int(item['duration']), "i": int(item['id']),"t":item['title']}  # 单个未学习信息
                lst.append(per)
        return lst
    except (requests.exceptions.ConnectionError, requests.exceptions.HTTPError, KeyError):
        print("获取未学习期数列表失败，跳过当前用户")
        return []
def send_request(url, payload, session, method='post'):
    try:
        if method == 'post':
            response = session.post(url, data=json.dumps(payload))
        else:
            response = session.get(url)
        if response.status_code == 200:
            return True
    except requests.exceptions.RequestException:
        return False
    return False
def learningRecords(r: requests.Session, openid: str, yid: int):
    # 记录学习第一条请求
    url = "https://www.jxqingtuan.cn/api-client/classRecord/learningRecords"
    payload = {"accessToken": openid, "course": yid, "retakes": 0}
    req = r.post(url, data=json.dumps(payload))
    if req.status_code == 200:
        return True
    else:
        return False
def addOrUpdateCourse(r: requests.Session, userid: str, orgid: str, duration: int, yid: int):
    # 记录学习第二条请求
    url = "https://www.jxqingtuan.cn/api-client/userScore/addOrUpdateCourse"
    payload = {"studyTime": duration + 100, "classId": yid, "userId": userid, "areaId1": orgid[:5],
               "areaId2": orgid[:9], "areaId3": orgid[:13], "areaId4": orgid, "status": 1, "retakes": 0}
    req = r.post(url, data=json.dumps(payload))
    if req.status_code == 200:
        if "无法学习" in req.json()['msg']:
            url = "https://www.jxqingtuan.cn/api-client/userScore/addOrUpdateCourse"
            payload = {"studyTime": duration + 100, "classId": yid, "userId": userid, "areaId1": orgid[:5],
                       "areaId2": orgid[:9], "areaId3": orgid[:13], "areaId4": orgid, "status": 1, "retakes": 1} # 这里改成1似乎可以补学
            r.post(url, data=json.dumps(payload))
        return True
    else:
        return False

if __name__ == '__main__':
    print(""" """)
    userlist_file = input("请输入用户信息文件的路径: ")
    start_line = int(input("请输入起始行号（从1开始）: "))
    userlist = [] # 用户信息
    try:
        with open(userlist_file, 'r', encoding='utf-8') as reader:
            for line_number, item in enumerate(reader, start=1):
                if line_number < start_line:
                    continue  # 跳过直到达到指定的起始行号
                try:
                    info = item.strip().split("|")
                    if len(info) != 5:
                        raise Exception(f"数据格式错误: {item}")
                    userlist.append([info[0], info[1], info[2], info[3], info[4]])
                except Exception as e:
                    print(f"处理第{line_number}行记录失败: {e}")
    except FileNotFoundError:
        print(f"文件不存在：{userlist_file}")
    except Exception as e:
        print(f"处理{userlist_file}文件异常: {e}")
    if userlist:
        print(f"成功处理{len(userlist)}条记录, 开始执行学习操作")
    else:
        print("没有成功获取到userlist数据")
    for index, userData in enumerate(userlist, start=start_line):
        try:
            openid = userData[3]  # 假设第四个元素是openid
            session = sessionBuilder(openid)
            initial_lst = retakesList(session)[:3]
            print(f"当前用户 {userData[0]} 的最近3个未学习期数: {initial_lst}")

            for item in initial_lst:
                step1 = learningRecords(session, openid=openid, yid=item['i'])
                if step1:
                    #time.sleep(1)
                    userid = userData[0]  # 假设第一个元素是userid
                    nid = userData[1]  # 假设第二个元素是nid
                    step2 = addOrUpdateCourse(session, userid=userid, orgid=nid, yid=item['i'], duration=item['d'])
                    if step2:
                        print("step1成功    step2成功")
                        print(f"成功完成学习期数: {item['i']}")
                    else:
                        continue
                else:
                    continue
                #time.sleep(1)
        except Exception as e:
            print(f"处理用户 {userData[2]} 时发生错误: {e}, 跳过当前用户")
            continue
        print(f"{userid} - 学习成功 (文件：{userlist_file}, 行号：{index})")

    print(f"成功完成{len(userlist)}次学习, 请等待后台数据刷新")
`

**Comment by Zzzz0077** [comment]
`
import json
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
stuInfo = []
def read_user_data(file_name):
    try:
        with open(file_name, 'r', encoding='utf-8') as reader:
            userlist = json.load(reader)
    except FileNotFoundError:
        print(f"{file_name} 文件不存在")
        userlist = {}
    except json.JSONDecodeError:
        print(f"{file_name} 文件格式不正确")
        userlist = {}

    return userlist
def sessionBuilder(openid: str):
    session = requests.session()
    session.headers = {
        "Connection": "keep-alive",
        # "Content-Length": "",
        "Authorization": openid,
        "charset": "utf-8",
        "requesttype": "",
        "openid": openid,
        "content-type": "application/json",
        "Accept-Encoding": "gzip,compress,br,deflate",
        "Referer": "https://servicewechat.com/wx88ccb2655c6720e2/51/page-frame.html",
        "User-Agent": "Mozilla/5.0 (Linux; Android 7.1.1; MI 6 Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/6.2 TBS/043807 Mobile Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN miniProgram"
    }
    session.verify = False # 如果需要开代理或者抓包请将其设置为False
    return session
def retakesList(r: requests.Session):
    try:
        url = "https://www.jxqingtuan.cn/api-client/classRecord/retakesList"
        response = r.get(url)
        response.raise_for_status()  # 将触发HTTP错误异常
        result = response.json()['data']['JxgqtClassVoList']
        lst = []  # 存放未学习期数
        for item in result:
            if item['learn'] == False:  # 还没学的
                per = {"d": int(item['duration']), "i": int(item['id']),"t":item['title']}  # 单个未学习信息
                lst.append(per)
        return lst
    except (requests.exceptions.ConnectionError, requests.exceptions.HTTPError, KeyError):
        print("获取未学习期数列表失败，跳过当前用户")
        return []
def send_request(url, payload, session, method='post'):
    try:
        if method == 'post':
            response = session.post(url, data=json.dumps(payload))
        else:
            response = session.get(url)
        if response.status_code == 200:
            return True
    except requests.exceptions.RequestException:
        return False
    return False
def learningRecords(r: requests.Session, openid: str, yid: int):
    # 记录学习第一条请求
    url = "https://www.jxqingtuan.cn/api-client/classRecord/learningRecords"
    payload = {"accessToken": openid, "course": yid, "retakes": 0}
    req = r.post(url, data=json.dumps(payload))
    if req.status_code == 200:
        return True
    else:
        return False
def addOrUpdateCourse(r: requests.Session, userid: str, orgid: str, duration: int, yid: int):
    # 记录学习第二条请求
    url = "https://www.jxqingtuan.cn/api-client/userScore/addOrUpdateCourse"
    payload = {"studyTime": duration + 100, "classId": yid, "userId": userid, "areaId1": orgid[:5],
               "areaId2": orgid[:9], "areaId3": orgid[:13], "areaId4": orgid, "status": 1, "retakes": 0}
    req = r.post(url, data=json.dumps(payload))
    if req.status_code == 200:
        if "无法学习" in req.json()['msg']:
            url = "https://www.jxqingtuan.cn/api-client/userScore/addOrUpdateCourse"
            payload = {"studyTime": duration + 100, "classId": yid, "userId": userid, "areaId1": orgid[:5],
                       "areaId2": orgid[:9], "areaId3": orgid[:13], "areaId4": orgid, "status": 1, "retakes": 1} # 这里改成1似乎可以补学
            r.post(url, data=json.dumps(payload))
        return True
    else:
        return False

if __name__ == '__main__':
    print(""" """)
    userlist_file = input("请输入用户信息文件的路径: ")
    start_line = int(input("请输入起始行号（从1开始）: "))
    userlist = [] # 用户信息
    try:
        with open(userlist_file, 'r', encoding='utf-8') as reader:
            for line_number, item in enumerate(reader, start=1):
                if line_number < start_line:
                    continue  # 跳过直到达到指定的起始行号
                try:
                    info = item.strip().split("|")
                    if len(info) != 5:
                        raise Exception(f"数据格式错误: {item}")
                    userlist.append([info[0], info[1], info[2], info[3], info[4]])
                except Exception as e:
                    print(f"处理第{line_number}行记录失败: {e}")
    except FileNotFoundError:
        print(f"文件不存在：{userlist_file}")
    except Exception as e:
        print(f"处理{userlist_file}文件异常: {e}")
    if userlist:
        print(f"成功处理{len(userlist)}条记录, 开始执行学习操作")
    else:
        print("没有成功获取到userlist数据")
    for index, userData in enumerate(userlist, start=start_line):
        try:
            openid = userData[3]  # 假设第四个元素是openid
            session = sessionBuilder(openid)
            initial_lst = retakesList(session)[:3]
            print(f"当前用户 {userData[0]} 的最近3个未学习期数: {initial_lst}")

            for item in initial_lst:
                step1 = learningRecords(session, openid=openid, yid=item['i'])
                if step1:
                    #time.sleep(1)
                    userid = userData[0]  # 假设第一个元素是userid
                    nid = userData[1]  # 假设第二个元素是nid
                    step2 = addOrUpdateCourse(session, userid=userid, orgid=nid, yid=item['i'], duration=item['d'])
                    if step2:
                        print("step1成功    step2成功")
                        print(f"成功完成学习期数: {item['i']}")
                    else:
                        continue
                else:
                    continue
                #time.sleep(1)
        except Exception as e:
            print(f"处理用户 {userData[2]} 时发生错误: {e}, 跳过当前用户")
            continue
        print(f"{userid} - 学习成功 (文件：{userlist_file}, 行号：{index})")

    print(f"成功完成{len(userlist)}次学习, 请等待后台数据刷新")
`

**Comment by Zzzz0077** [comment]
`
import json
import requests
import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
stuInfo = []
def read_user_data(file_name):
    try:
        with open(file_name, 'r', encoding='utf-8') as reader:
            userlist = json.load(reader)
    except FileNotFoundError:
        print(f"{file_name} 文件不存在")
        userlist = {}
    except json.JSONDecodeError:
        print(f"{file_name} 文件格式不正确")
        userlist = {}

    return userlist
def sessionBuilder(openid: str):
    session = requests.session()
    session.headers = {
        "Connection": "keep-alive",
        # "Content-Length": "",
        "Authorization": openid,
        "charset": "utf-8",
        "requesttype": "",
        "openid": openid,
        "content-type": "application/json",
        "Accept-Encoding": "gzip,compress,br,deflate",
        "Referer": "https://servicewechat.com/wx88ccb2655c6720e2/51/page-frame.html",
        "User-Agent": "Mozilla/5.0 (Linux; Android 7.1.1; MI 6 Build/NMF26X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/57.0.2987.132 MQQBrowser/6.2 TBS/043807 Mobile Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN MicroMessenger/6.6.1.1220(0x26060135) NetType/4G Language/zh_CN miniProgram"
    }
    session.verify = False # 如果需要开代理或者抓包请将其设置为False
    return session
def retakesList(r: requests.Session):
    try:
        url = "https://www.jxqingtuan.cn/api-client/classRecord/retakesList"
        response = r.get(url)
        response.raise_for_status()  # 将触发HTTP错误异常
        result = response.json()['data']['JxgqtClassVoList']
        lst = []  # 存放未学习期数
        for item in result:
            if item['learn'] == False:  # 还没学的
                per = {"d": int(item['duration']), "i": int(item['id']),"t":item['title']}  # 单个未学习信息
                lst.append(per)
        return lst
    except (requests.exceptions.ConnectionError, requests.exceptions.HTTPError, KeyError):
        print("获取未学习期数列表失败，跳过当前用户")
        return []
def send_request(url, payload, session, method='post'):
    try:
        if method == 'post':
            response = session.post(url, data=json.dumps(payload))
        else:
            response = session.get(url)
        if response.status_code == 200:
            return True
    except requests.exceptions.RequestException:
        return False
    return False
def learningRecords(r: requests.Session, openid: str, yid: int):
    # 记录学习第一条请求
    url = "https://www.jxqingtuan.cn/api-client/classRecord/learningRecords"
    payload = {"accessToken": openid, "course": yid, "retakes": 0}
    req = r.post(url, data=json.dumps(payload))
    if req.status_code == 200:
        return True
    else:
        return False
def addOrUpdateCourse(r: requests.Session, userid: str, orgid: str, duration: int, yid: int):
    # 记录学习第二条请求
    url = "https://www.jxqingtuan.cn/api-client/userScore/addOrUpdateCourse"
    payload = {"studyTime": duration + 100, "classId": yid, "userId": userid, "areaId1": orgid[:5],
               "areaId2": orgid[:9], "areaId3": orgid[:13], "areaId4": orgid, "status": 1, "retakes": 0}
    req = r.post(url, data=json.dumps(payload))
    if req.status_code == 200:
        if "无法学习" in req.json()['msg']:
            url = "https://www.jxqingtuan.cn/api-client/userScore/addOrUpdateCourse"
            payload = {"studyTime": duration + 100, "classId": yid, "userId": userid, "areaId1": orgid[:5],
                       "areaId2": orgid[:9], "areaId3": orgid[:13], "areaId4": orgid, "status": 1, "retakes": 1} # 这里改成1似乎可以补学
            r.post(url, data=json.dumps(payload))
        return True
    else:
        return False

if __name__ == '__main__':
    print(""" """)
    userlist_file = input("请输入用户信息文件的路径: ")
    start_line = int(input("请输入起始行号（从1开始）: "))
    userlist = [] # 用户信息
    try:
        with open(userlist_file, 'r', encoding='utf-8') as reader:
            for line_number, item in enumerate(reader, start=1):
                if line_number < start_line:
                    continue  # 跳过直到达到指定的起始行号
                try:
                    info = item.strip().split("|")
                    if len(info) != 5:
                        raise Exception(f"数据格式错误: {item}")
                    userlist.append([info[0], info[1], info[2], info[3], info[4]])
                except Exception as e:
                    print(f"处理第{line_number}行记录失败: {e}")
    except FileNotFoundError:
        print(f"文件不存在：{userlist_file}")
    except Exception as e:
        print(f"处理{userlist_file}文件异常: {e}")
    if userlist:
        print(f"成功处理{len(userlist)}条记录, 开始执行学习操作")
    else:
        print("没有成功获取到userlist数据")
    for index, userData in enumerate(userlist, start=start_line):
        try:
            openid = userData[3]  # 假设第四个元素是openid
            session = sessionBuilder(openid)
            initial_lst = retakesList(session)[:3]
            print(f"当前用户 {userData[0]} 的最近3个未学习期数: {initial_lst}")

            for item in initial_lst:
                step1 = learningRecords(session, openid=openid, yid=item['i'])
                if step1:
                    #time.sleep(1)
                    userid = userData[0]  # 假设第一个元素是userid
                    nid = userData[1]  # 假设第二个元素是nid
                    step2 = addOrUpdateCourse(session, userid=userid, orgid=nid, yid=item['i'], duration=item['d'])
                    if step2:
                        print("step1成功    step2成功")
                        print(f"成功完成学习期数: {item['i']}")
                    else:
                        continue
                else:
                    continue
                #time.sleep(1)
        except Exception as e:
            print(f"处理用户 {userData[2]} 时发生错误: {e}, 跳过当前用户")
            continue
        print(f"{userid} - 学习成功 (文件：{userlist_file}, 行号：{index})")

    print(f"成功完成{len(userlist)}次学习, 请等待后台数据刷新")
`

**Comment by Zzzz0077** [comment]
评论区好像不太好上传代码，试了几次都是这种无格式的

**Comment by Zzzz0077** [comment]
我刚刚新建了一个git项目，那里可以比较方便的复制和查看代码，辛苦作者帮我找找bug，感激不尽！！！
