### ISSUE TITLE
作者大大，后台好像还是不能记录到打卡数据

### ISSUE THREAD

**Issue by Zzzz0077** [xiaoWangSec/jx-qndxx#2]
我刚刚试着刷了50个数据到后台，等了半个小时发现后台还是没有数据，也可能是我哪里没有操作好，作者大大能教一下我嘛，团支书真的很需要这个，有偿,WX:zxzx020501

**Comment by Zzzz0077** [comment]
![QQ截图20230715222244](https://github.com/xiaoWangSec/jx-qndxx/assets/131767959/cf839e0e-5481-4e92-9fea-5ae73dfefc4c)

**Comment by xiaoWangSec** [comment]
确定openid是正确的吗

**Comment by xiaoWangSec** [comment]
已重构代码, 请仔细阅读`README.md`文件中的使用方法

**Comment by Zzzz0077** [comment]
可以打卡了，谢谢作者大大的及时更新和回复，救了团支书一命，有打赏通道嘛，我要支持一下！！！太感谢了！！！！！
