### ISSUE TITLE
后台还是没记录

### ISSUE THREAD

**Issue by Zzzz0077** [xiaoWangSec/jx-qndxx#5]
用代码跑完以后，显示已经成功获取积分和学习记录，但是后台还是没记录，作者大大能解答一下嘛

**Comment by xiaoWangSec** [comment]
我测试是有记录的, 只不过会很晚才在后台显示, 而且接口容易报错(404, 500, 502...)
如果你10月的那个版本没有用过的话, 需要先执行以下那个更新手机号的脚本, 确保所有同学都已经填写了手机号(脚本会随机手机号填入)
之后再执行最新的学习脚本, 如果报错建议多次尝试

**Comment by Zzzz0077** [comment]
10月那个版本我用过了，电话号码啥的都有，上一期也能正常刷人数进去，就是这一期好奇怪，刷完后台就是没记录到人数，不知道是刷进去还是没刷进去
![QQ截图20231122142615](https://github.com/xiaoWangSec/jx-qndxx/assets/131767959/6566644d-8904-4628-9a12-3b0b26efe958)

**Comment by Zzzz0077** [comment]
7个小时了，后台还是没有记录，作者大大能不能帮我看一下，很急，有偿！！！wx：zxzx020501

**Comment by xiaoWangSec** [comment]
现在有记录了吧, 应该是系统延迟了

**Comment by Zzzz0077** [comment]
有了有了，一直没看邮箱，没来得及回复，这个大学习后台系统也太lj了吧，缓存要缓这么久，一整天后台都没有更新记录，群里那么多人都在抱怨为什么学了没记录，他那边都不想办法维护一下，而且登陆后台还经常登不上去！！！！！
