### ISSUE TITLE
好像又出问题了

### ISSUE THREAD

**Issue by Zzzz0077** [xiaoWangSec/jx-qndxx#8]
今天上午刷的，后台一直没有记录，显示是成功记录学习，成功获取积分，昨天刷的后台都有记录，奇怪了，另外省里面开通了补学功能，作者大大有空更新一下脚本，看看是啥原因不，感谢！！！

**Comment by xiaoWangSec** [comment]
主题2期1月28日提交很快刷新, 后台没显示可能是延迟.

**Comment by Zzzz0077** [comment]
对，之前刷进去马上后台就能看得到，但是今天刷进去后台一直没有显示，他们正常打卡的也能很快在后台显示，等晚上看看更新了不

**Comment by Zzzz0077** [comment]
一天来了，后台还是没有记录，是不是因为H5在维护的原因呀

**Comment by Zzzz0077** [comment]
今天下午又重新刷了一次，还是没记录，作者大大有空测试一下嘛

**Comment by xiaoWangSec** [comment]
1. [https://github.com/xiaoWangSec/jx-qndxx/blob/master/jx-qndxx.py#L72](https://github.com/xiaoWangSec/jx-qndxx/blob/master/jx-qndxx.py#L72) 此处的获取学习链接的接口现在无法获取到学习链接: `"studyUrl":"null"`
2. 目前判断学习成果与否是根据返回包中的code是否为200, 是则认为学习成果, 否则不会输出结果, 如果请求失败则会抛出异常
3. 现在学习失败极有可能是因为72行的接口不返回学习链接导致, `{"code":500106,"msg":"参数有为空项，请检查！","data":{}}`

**Comment by xiaoWangSec** [comment]
接口应该是没有问题的, 只是后台主题团课根本没有填入学习链接, 现在电脑端已经不能正常打开小程序了, 提示需要手机打开, 后续有时间再看看具体怎么解决

**Comment by Zzzz0077** [comment]
url = {
        'data_login':'http://106.225.141.143:8103/',
        'qn_url':'http://www.jxqingtuan.cn/html/?accessToken=',
        'study': 'http://www.jxqingtuan.cn/pub/pub/vol/volClass/join?accessToken=',
        'get_data_token':'http://106.225.141.143:8103/portal/vol/jxgqtClassRecord/list?',
        "get_title":"http://www.jxqingtuan.cn/pub/pub/vol/volClass/index",
        "addscore":"http://www.jxqingtuan.cn/pub/pub/vol/member/addScoreInfo",
        "get_person_info":"http://www.jxqingtuan.cn/pub/pub/vol/member/info accessToken="
}
def gettittle():
    global datas
    url = config.url['get_title']
    res = requests.get(url,timeout=5).text
    res = json.loads(res)["list"][0]
    # print(res)
    id = res["id"]
    tittle = res["title"]
    url = res["url"]
    t = "第{}期".format(id) + tittle
    print("第{}期".format(id) + "青年大学习标题：" + tittle + "\n" + "青年大学习学习链接：" + url)
    return id, tittle, url
   这是另外一个作者写的获取学习链接的方式，可以参考一下
   奇怪的是，前两天那会可以打卡的时候是可以正常学习的，难道后面省里面又把团课的学习链接给撤下来了嘛，29号的时候数据库还满了，我这边有省里面建的大学习的交流群，有需要的信息可以随时联系我

**Comment by Zzzz0077** [comment]
url = {
        'data_login':'http://106.225.141.143:8103/',
        'qn_url':'http://www.jxqingtuan.cn/html/?accessToken=',
        'study': 'http://www.jxqingtuan.cn/pub/pub/vol/volClass/join?accessToken=',
        'get_data_token':'http://106.225.141.143:8103/portal/vol/jxgqtClassRecord/list?',
        "get_title":"http://www.jxqingtuan.cn/pub/pub/vol/volClass/index",
        "addscore":"http://www.jxqingtuan.cn/pub/pub/vol/member/addScoreInfo",
        "get_person_info":"http://www.jxqingtuan.cn/pub/pub/vol/member/info accessToken="
}
def gettittle():
    global datas
    url = config.url['get_title']
    res = requests.get(url,timeout=5).text
    res = json.loads(res)["list"][0]
    # print(res)
    id = res["id"]
    tittle = res["title"]
    url = res["url"]
    t = "第{}期".format(id) + tittle
    print("第{}期".format(id) + "青年大学习标题：" + tittle + "\n" + "青年大学习学习链接：" + url)
    return id, tittle, url
   这是另外一个作者写的获取学习链接的方式，可以参考一下
   奇怪的是，前两天那会可以打卡的时候是可以正常学习的，难道后面省里面又把团课的学习链接给撤下来了嘛，29号的时候数据库还满了，我这边有省里面建的大学习的交流群，有需要的信息可以随时联系我

**Comment by xiaoWangSec** [comment]
我觉得可能是采用了新的记录方式，现在小程序不能点进去就退出来记录学习，必须要学够时间

**Comment by Zzzz0077** [comment]
没错，好像就是最近添加的学习时长，搞得真的是越来越复杂了，头疼

**Comment by xiaoWangSec** [comment]
可以解包小程序➕抓包分析是如何记录学习情况

**Comment by Zzzz0077** [comment]
嗯嗯这个学期还有最后一期大学习，主题团课的第三期，团支书太难了5555，作者大大有时间可以找找解决办法，有需要随时联系我，提前祝你新年快乐！！！感谢！！！

**Comment by koinouta1** [comment]
抓了个包，你替换openid看看有没有用，import requests
import json


OpenID=" "
# 请求头部
headers = {
    "Host": "www.jxqingtuan.cn",
    "Connection": "keep-alive",
    "Content-Length": "70",
    "Authorization": "oE0ST62PC-rRhSQDrYUZXtgZ4e1U",
    "charset": "utf-8",
    "requesttype": "",
    "OpenID": OpenID,
    "User-Agent": "Mozilla/5.0 (Linux; Android 14; M2006J10C Build/UQ1A.231205.015; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36 XWEB/1160065 MMWEBSDK/20231202 MMWEBID/1767 MicroMessenger/8.0.47.2560(0x28002F32) WeChat/arm64 Weixin NetType/WIFI Language/zh_CN ABI/arm64 MiniProgramEnv/android",
    "Content-Type": "application/json;charset=UTF-8;",
    "Accept-Encoding": "gzip,compress,br,deflate",
    "Referer": "https://servicewechat.com/wx88ccb2655c6720e2/50/page-frame.html"
}

# 请求体
body_data = {
    "accessToken": OpenID, #微信openid
    "course": 66,  #课程id号
    "retakes": 0
}

# 请求地址
url = "https://www.jxqingtuan.cn/api-client/classRecord/learningRecords"

# 发送POST请求
response = requests.post(url, headers=headers, json=body_data)

# 输出响应信息
print("响应状态码:", response.status_code)
print("响应内容:")
print(json.dumps(response.json(), indent=2))

**Comment by Zzzz0077** [comment]
第三期团课又来了，作者大大看看能不能调试一下，需要账号测试的话可以滴滴我

**Comment by xiaoWangSec** [comment]
> 第三期团课又来了，作者大大看看能不能调试一下，需要账号测试的话可以滴滴我

已经测试好了, 可以批量补学和批量代学, 等下会重构代码再更新

**Comment by Zzzz0077** [comment]
好的好的，感谢作者大大，我还有一个问题就是开着翻墙进行批量代学的时候要么就是无法记录学习，要么就是无法获取积分，这个能优化一下嘛

**Comment by xiaoWangSec** [comment]
已更新, 请使用[appletYouthStudy.py](https://github.com/xiaoWangSec/jx-qndxx/blob/master/appletYouthStudy.py)

使用时请将最新脚本与上一版本用户数据文件`users.json`放置在同一目录下运行

暂未添加新增用户接口

需要开启代理或者抓包软件运行脚本请取消注释代码第34行, 设置`session.verify = False`
