### ISSUE TITLE
补学功能有点疑问

### ISSUE THREAD

**Issue by Zzzz0077** [xiaoWangSec/jx-qndxx#9]
我试了一下补学功能，寒假三期的主题团课是补学不了，团省委好像把补学的入口都给关掉了，2024年第一期的补学入口是开放的，我想补学一下这一期，但是刷了两遍后台还是没有记录，作者大大有空能再测试一下嘛，需要数据的话我这边可以提供

**Comment by xiaoWangSec** [comment]
学习信息(期数, 是否学习)是通过接口取得的, [第40行](https://github.com/xiaoWangSec/jx-qndxx/blob/master/appletYouthStudy.py#L40)

现在尝试补学, 提示`msg=课程已结束，无法学习！`, 应该是已经关闭了补学

**Comment by xiaoWangSec** [comment]
用手机可以完成补学? 那可能就是换了接口了

目前似乎是需要看满时长才能够返回, 否则会提示学习未完成

**Comment by Zzzz0077** [comment]
喔喔这样子，这个学习的门槛真的是越来越高了，以前点一下后台就会有记录的，补学的接口作者大大有时间能不能更新一下，感谢
